[package]
name = "MiniMiners"               
version = "0.0.1" 
license = "MPL 2.0"              
authors = ["Medet Ahmetson (admin@blocklords.io)"]

[dependencies]
Sui = { local = "../../sui/crates/sui-framework" }

[addresses]  
mini_miners = "0x0"
